### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by CasanierXI** [PeterDaveHello/dnslow.me#7]
Perhaps you can provide the ad blocklists you use🙂

**Comment by PeterDaveHello** [comment]
@CasanierXI Thanks for your suggestion, let's not delete it, it's good to know!

**Comment by CasanierXI** [comment]
OK, if that's what you want and I can't find the option to delete😅

**Comment by CasanierXI** [comment]
https://github.com/PeterDaveHello/dnslow.me/blob/master/adguardhome/conf/AdGuardHome.yaml
在這裡似乎可以看到您用的Ad filters。因為我是個電腦外行，很抱歉現在才發現...
再次感謝！♥️
